FROM registry.access.redhat.com/ubi9/python-311:1-62.1714671026
WORKDIR /sentiment
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /sentiment/requirements.txt
COPY sentiment.py .
EXPOSE 8501
ENTRYPOINT [ "streamlit", "run", "summarizer.py" ]
